name:                andos
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

executables:
  andos-exe:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    dependencies:
    - andos
    - arithmoi
    - reflection

library:
  source-dirs: src
  dependencies:
  - arithmoi
  - bytestring
  - mono-traversable
  - random
  - reflection
  - split
  - text
  - vector
  - yaml
  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities

tests:
  test-all:
    main:        Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    dependencies:
    - andos
    - arithmoi
    - bytestring
    - mono-traversable
    - QuickCheck
    - quickcheck-instances
    - tasty
    - tasty-quickcheck
    - random
